# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Marcel Eichner
email: love@ephigenia.de
description: Website of Marcel Eichner, full-stack Javascript & PHP web developer from Berlin.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.marceleichner.de" # the base hostname & protocol for your site
twitter_username: ephigenia
github_username:  Ephigenia
gitlab_username: ephigenia
xing_username: Marcel_Eichner
linkedin_username: ephigenia

analytics:
  google:
    tracking_id: 'UA-80368234-1'

# Build settings
markdown: kramdown

timezone: Europe/Berlin
